name: NoMobGriefing
main: com.itsharv.nomobgriefing.NoMobGriefing
version: 0.1
author: Harv

commands:
  nmg:
    description: Shows help and info about the NoMobGriefin plugin.
    usage: /nmg
    aliases: [nomobgriefing]

permissions:
  nmg.*:
    description: Gives acces to all NoMobGriefing commands.
    children:
      nmg.list: true
      nmg.zombie:true
      nmg.creeper: true
      nmg.enderman: true
      nmg.ghast: true
      nmg.wither: true
      nmg.enderdragon: true
      nmg.tnt: true
  nmg.list:
    description: Allows the user to use the list command.
    default: true
  nmg.creeper:
    description: Allows the user to enable/disable creepers blowing up blocks.
    default: op
  nmg.zombie:
    description: Allows the user to enable/disable zombies destroying doors.
    default: op
  nmg.enderman:
    description: Allows the user to enable/disable endermen picking up blocks.
    default: op
  nmg.snowgolem:
    description: Allows the user to enable/disable snowgolems leaving snow trails.
    default: op
  nmg.ghast:
    description: Allows the user to enable/disable ghasts blowing up blocks.
    default: op
  nmg.wither:
    description: Allows the user to enable/disable withers destroying blocks.
    default: op
  nmg.enderdragon:
    description: Allows the user to enable/disable the enderdragon destroying blocks.
    default: op
  nmg.tnt:
    description: Allows the user to enable/disable tnt blowing up blocks.
    default: op